export const dataValue = [
  {
    id: 1,
    first_name: "Fedora",
    last_name: "Ballam",
    email: "fballam0@sciencedirect.com",
    gender: "Female",
  },
  {
    id: 2,
    first_name: "Dasha",
    last_name: "Effnert",
    email: "deffnert1@abc.net.au",
    gender: "Female",
  },
  {
    id: 3,
    first_name: "Jemimah",
    last_name: "Rouzet",
    email: "jrouzet2@guardian.co.uk",
    gender: "Female",
  },
  {
    id: 4,
    first_name: "Prince",
    last_name: "Perulli",
    email: "pperulli3@pen.io",
    gender: "Male",
  },
  {
    id: 5,
    first_name: "Kendal",
    last_name: "Graalman",
    email: "kgraalman4@netlog.com",
    gender: "Male",
  },
  {
    id: 6,
    first_name: "Christan",
    last_name: "Vellacott",
    email: "cvellacott5@elpais.com",
    gender: "Female",
  },
  {
    id: 7,
    first_name: "Mallissa",
    last_name: "Slewcock",
    email: "mslewcock6@hatena.ne.jp",
    gender: "Female",
  },
  {
    id: 8,
    first_name: "Karyl",
    last_name: "Dunridge",
    email: "kdunridge7@furl.net",
    gender: "Female",
  },
  {
    id: 9,
    first_name: "Frederich",
    last_name: "Pittoli",
    email: "fpittoli8@indiegogo.com",
    gender: "Male",
  },
  {
    id: 10,
    first_name: "Keene",
    last_name: "Castletine",
    email: "kcastletine9@icio.us",
    gender: "Male",
  },
  {
    id: 11,
    first_name: "Georgeanne",
    last_name: "Pillington",
    email: "gpillingtona@eepurl.com",
    gender: "Female",
  },
  {
    id: 12,
    first_name: "Konstanze",
    last_name: "Smithin",
    email: "ksmithinb@prlog.org",
    gender: "Genderfluid",
  },
  {
    id: 13,
    first_name: "Jaymee",
    last_name: "Schutt",
    email: "jschuttc@blogtalkradio.com",
    gender: "Female",
  },
  {
    id: 14,
    first_name: "Dorena",
    last_name: "Martins",
    email: "dmartinsd@pbs.org",
    gender: "Female",
  },
  {
    id: 15,
    first_name: "Lib",
    last_name: "Chaffey",
    email: "lchaffeye@mapy.cz",
    gender: "Female",
  },
  {
    id: 16,
    first_name: "Keary",
    last_name: "Waith",
    email: "kwaithf@epa.gov",
    gender: "Male",
  },
  {
    id: 17,
    first_name: "Emiline",
    last_name: "Antalffy",
    email: "eantalffyg@sitemeter.com",
    gender: "Female",
  },
  {
    id: 18,
    first_name: "Delia",
    last_name: "Base",
    email: "dbaseh@over-blog.com",
    gender: "Female",
  },
  {
    id: 19,
    first_name: "Zacherie",
    last_name: "Willstrop",
    email: "zwillstropi@globo.com",
    gender: "Male",
  },
  {
    id: 20,
    first_name: "Stevena",
    last_name: "Izachik",
    email: "sizachikj@hp.com",
    gender: "Female",
  },
];
